name: CI

on:
  push:
    branches:
      - main

permissions:
  contents: write # This grants the necessary write permissions to push to the repository
  pages: write    # Recommended for GitHub Pages deployments
  id-token: write # If your GitHub Pages uses OIDC for authentication (optional, but good practice)

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist/public
          # publish_branch: gh-pages # This defaults to 'gh-pages', so you might not need to explicitly set it unless you use a different branch
